package sbdb

import (
	"testing"
)

func Test_queryBuilder_Build(t *testing.T) {
	tests := []struct {
		name string
		args *SmallBodyOptions
		want string
	}{
		{
			name: "Date min is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "1-2-2020",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "date-min=1-2-2020&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		}, {
			name: "Date max is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "1-2-2020",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "date-max=1-2-2020&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		}, {
			name: "Distance min is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         ".75",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "dist-min=.75&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		}, {
			name: "Distance max is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         ".7",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "dist-max=.7&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "H min is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                ".12",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "h-min=.12&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "H max is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                ".2",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "h-max=.2&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Velocity Infinity max is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "1.3",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "v-inf-max=1.3&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Velocity Infinity Min is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      ".001",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "v-inf-min=.001&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Velocity Relative max is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "1",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "vel-rel-max=1&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Velocity relative min is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "1",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "vel-rel-min=1&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Class is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "TestClass",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "class=TestClass&pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "PHA is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 true,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=true&nea=false&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Nea is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 true,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=true&comet=false&nea-comet=false&neo=false&fullname=false",
		},{
			name: "Comet is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               true,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=true&nea-comet=false&neo=false&fullname=false",
		},{
			name: "NeaComet is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            true,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=true&neo=false&fullname=false",
		},{
			name: "Neo is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 true,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=true&fullname=false",
		},{
			name: "Kind is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "TestKind",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&kind=TestKind&fullname=false",
		},{
			name: "SPK is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "TestSPK",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&spk=TestSPK&fullname=false",
		},{
			name: "Designation is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "TestDesignation",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&designation=TestDesignation&fullname=false",
		},{
			name: "Body is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "TestBody",
				Sort:                "",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&body=TestBody&fullname=false",
		},{
			name: "Sort is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "TestSort",
				Limit:               "",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&sort=TestSort&fullname=false",
		},{
			name: "Limit is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "TestLimit",
				FullName:            false,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&limit=TestLimit&fullname=false",
		},{
			name: "Fullname is only option for query parameters",
			args: &SmallBodyOptions{
				DateMin:             "",
				DateMax:             "",
				DistanceMin:         "",
				DistanceMax:         "",
				HMin:                "",
				HMax:                "",
				VelocityInfMax:      "",
				VelocityInfMin:      "",
				VelocityRelativeMax: "",
				VelocityRelativeMin: "",
				Class:               "",
				Pha:                 false,
				Nea:                 false,
				Comet:               false,
				NeaComet:            false,
				Neo:                 false,
				Kind:                "",
				Spk:                 "",
				Designation:         "",
				Body:                "",
				Sort:                "",
				Limit:               "",
				FullName:            true,
			},
			want: "pha=false&nea=false&comet=false&nea-comet=false&neo=false&fullname=true",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			qb := &queryBuilder{}
			if got := qb.Build(tt.args); got != tt.want {
				t.Errorf("Build() = %v, want %v", got, tt.want)
			}
		})
	}
}
